project:
  type: website
  output-dir: _site
  pre-render: version_config.py

format:
  html:
    toc: true
    toc-depth: 5
    css: style.css
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap
    highlight-style: github
    code-block-bg: true
    code-block-border-left: secondary

brand: _brand.yml

website:
  title: "pxwebpy"
  description: "Client library for the PxWeb API to easily load data into a DataFrame."
  repo-url: https://github.com/stefur/pxwebpy
  repo-actions: [issue]
  page-navigation: true
  navbar:
    background: primary
    pinned: true
    search: true
    left:
      - text: "Get started"
        file: index.qmd
      - text: "Examples"
        file: examples.qmd
      - text: "Reference"
        file: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/stefur/pxwebpy
        target: _blank

quartodoc:
  title: "pxwebpy v{{< env VERSION >}}"
  package: pxweb
  options:
    include_attributes: false
    dynamic: false
  render_interlinks: true
  renderer:
    style: markdown
    table_style: description-list
    show_signature_annotations: true
  sections:
    - title: API interaction
      desc: |
        Tools to explore tables and get data from the PxWeb API.
      contents:
        - name: PxApi
        - get_known_apis

filters:
  - interlinks

interlinks:
  aliases:
    pxweb: null
  autolink: true