project:
  type: website
  output-dir: _site
  pre-render: version_config.py

encoding: utf-8

format:
  html:
    toc: true
    toc-depth: 5
    css: style.css
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap

brand: _brand.yml

website:
  title: "pxwebpy {{< env VERSION >}}"
  description: "Getting data from the PxWeb API into a dataframe"
  repo-url: https://github.com/stefur/pxwebpy
  repo-actions: [issue]
  page-navigation: true
  navbar:
    background: primary
    pinned: true
    search: true
    left:
      - text: "Get started"
        file: index.qmd
      - text: "Examples"
        file: examples.qmd
      - text: "Reference"
        file: reference/index.qmd
    right:
      - icon: github
        href: https://github.com/stefur/pxwebpy
        target: _blank

quartodoc:
  title: Reference
  package: pxwebpy
  options:
    include_attributes: false
    dynamic: false
  render_interlinks: true
  sections:
    - title: API interaction
      desc: |
        Tools to explore tables and get data from the PxWeb API.
      contents:
        - name: PxWebApi
        - get_known_apis

filters:
  - interlinks

interlinks:
  aliases:
    pxwebpy: null
  autolink: true