---
title: Development
jupyter: python3
---

Thank you for your interest in the development of `pxwebpy`!  
This page explains how you can contribute. All improvements to code, documentation, and tests are welcome.

## Setting up `uv` and the virtual environment

This project is set up to use [`uv`](https://docs.astral.sh/uv/) to manage Python and
dependencies. First, be sure you
[have `uv` installed](https://docs.astral.sh/uv/getting-started/installation/).

To install dependencies and set up the virtual environment:
```bash
# Clone the repository
git clone https://github.com/stefur/pxwebpy.git
cd pxwebpy

# Sync dependencies and create the virtual environment
uv sync
```

For more details on how to use `uv`, head over to the [`uv` docs](https://docs.astral.sh/uv/).

## Formatting

### Code
`ruff` is used for linting and formatting. Currently, no pre-commit hooks are configured. Instead `ruff` is included in the project as a development dependency.  
  
The `ruff` command can be used in an activated virtual environment or using `uv run` to perform `ruff check` and `ruff format`. See the [documentation](https://docs.astral.sh/ruff/installation/) on how to otherwise install `ruff`.

### Docstrings
Follow the [`NumPy`](https://numpydoc.readthedocs.io/en/latest/format.html#overview) style guide when writing docstrings. This is important for being able to [build the documentation](#building-the-documentation).

## Running tests
Tests are run using `pytest`, typically via `uv run`:

```bash
uv run pytest   # all tests
uv run pytest -s tests/test_client.py  # one test file
uv run pytest -s tests/test_client.py::test_call_raises_http_error # one specific test
```

To check test coverage:

```bash
uv run pytest --cov=src --cov-report=term
```

Some tests utilize [`syrupy`](https://github.com/syrupy-project/syrupy) for snapshot testing to ensure consistency. If snapshots for some reason need to be updated run `uv run pytest --snapshot-update`.

## Building the documentation
Documentation is built using [`quartodoc`](https://github.com/machow/quartodoc), thus you also need [`quarto`](https://quarto.org/docs/get-started/) installed on your machine if you wish to build the documentation locally. This is usually a good idea to check that the output looks as expected. The documentation is automatically built and published upon each release.

With `quarto` installed, building the documentation is done in two steps:

```bash
uv run quartodoc build
uv run quarto render
```

The rendered output is found in the folder called `_site`.

## Submitting changes
When you’re ready to contribute:  

1. Clone the repository and create a new branch for your changes.  
2. Ensure that:  
    * All tests pass locally (`uv run pytest`)  
    * Code is linted and formatted (`uv run ruff check && uv run ruff format`)  
    * Documentation (if relevant) builds successfully  
3. Open a pull request to the `main` branch.  
